[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_function = test_*

# Thêm src <Source> mã nguồn vào Python path để import
pythonpath = src

# Markers
markers = 
smoke: Smoke Test
regression: Regression Test
loginpage: Test for Login page
homepage: Test for Home page
function: Test for function

# Option
addopts =
    -v
    --strict-markers
    --html=reports/report.html
    --self-contained-html